# Banco de produção
spring.datasource.url=jdbc:postgresql://<host_producao>:5432/ranking_vendas
spring.datasource.username=usuario_prod
spring.datasource.password=senha_prod

# Hibernate não cria tabelas automaticamente em produção
spring.jpa.hibernate.ddl-auto=validate

# Logs reduzidos
logging.level.org.hibernate.SQL=INFO
